version: '3'
services:
  adalite-backend:
    build: .
    ports:
      - "${BACKEND_SERVICE_PORT}:8080"
    volumes:
      - ${DATA_PATH}/server.log:/usr/app/server.log
    depends_on:
      - postgres
    container_name: adalite-backend-${SUFIX}
    environment:
      DB: icarus_mainnet_1
      name: adalite-backend-${SUFIX}
  icarus-importer:
    image: cardano-container-mainnet
    volumes:
      - ${DATA_PATH}/icarus_mainnet:/wallet/mainnet
    depends_on:
      - adalite-backend
    container_name: icarus-importer-${SUFIX}
    command: wait-for-it.sh adalite-backend:8080 -t 3600 -- cardano-start -- --runtime-args "--postgres-name icarus_mainnet_1 --postgres-user ${POSTGRES_USER} --postgres-password ${POSTGRES_PASSWORD} --postgres-host postgres --postgres-port 5432 --no-tls"
  postgres:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DATA_PATH}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: icarus_mainnet_1
    container_name: postgres-${SUFIX}
